import type { NextPage } from "next";
import Head from "next/head";
import BannerOne from "../components/Sections/bannerOne";
import JourneySection from "../components/Sections/JourneySection";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <main className={styles.main}>
        <BannerOne></BannerOne>
        <JourneySection></JourneySection>
      </main>
    </div>
  );
};

export default Home;
